import './globals.css';
import { Inter } from 'next/font/google';
import SupabaseProvider from './supabase-provider';
import { createServerComponentSupabaseClient } from '@supabase/auth-helpers-nextjs';
import { headers, cookies } from 'next/headers';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// async function getSession(supabase: SupabaseClient) {
//   const session = await supabase.auth.getSession();
//   return session.data.session
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentSupabaseClient({
    supabaseUrl: process.env.NEXT_PUBLIC_SUP_URL || '',
    supabaseKey: process.env.NEXT_PUBLIC_SUP_A_KEY || '',
    headers,
    cookies,
  });

  const session = await supabase.auth.getSession();

  // console.log('this is from serber!', session.data.session?.user);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}

        <SupabaseProvider session={session.data.session}>
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
